### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by zce** [zce/zce.me#19]
## content config

```js
const collections = {
  posts: {
    type: 'post',
    template: 'post',
    permalink: '/{year}/{month}/{slug}/',
    draft: false,
    private: false,
    featured: false,
    comment: true,
    authors: ['Lei Wang'],
    categories: ['Uncategorized'],
    tags: ['Untagged']
  },
  pages: {
    type: 'page',
    template: 'page',
    permalink: '/{slug}/',
    draft: false,
    private: false,
    featured: false,
    comment: false,
    authors: ['Lei Wang'],
    categories: ['Uncategorized'],
    tags: ['Untagged']
  }
}

const taxonomies = {
  authors: {
    type: 'author',
    template: 'author',
    permalink: '/authors/{slug}/'
  },
  categories: {
    type: 'category',
    template: 'category',
    permalink: '/categories/{slug}/'
  },
  tags: {
    type: 'tag',
    template: 'tag',
    permalink: '/tags/{slug}/'
  }
}
```

**Comment by zce** [comment]
## gatsby-transformer-yaml

```js
const { load } = require('js-yaml')
const { singular } = require('pluralize')
const { upperFirst, camelCase } = require('lodash')

exports.onCreateNode = async ({
  node,
  actions,
  loadNodeContent,
  createNodeId,
  createContentDigest
}) => {
  if (node.internal.mediaType !== 'text/yaml') return

  const content = await loadNodeContent(node)
  const parsedContent = load(content)

  const list = Array.isArray(parsedContent) ? parsedContent : [parsedContent]

  const type = upperFirst(camelCase(singular(node.name)))

  list.forEach((item, i) => {
    const yamlNode = {
      ...item,
      id: item.id || createNodeId(`${node.id} [${i}] >>> YAML`),
      children: [],
      parent: node.id,
      internal: {
        contentDigest: createContentDigest(item),
        type: `${type}Yaml`
      }
    }

    actions.createNode(yamlNode)
    actions.createParentChildLink({ parent: node, child: yamlNode })
  })
}
```

**Comment by zce** [comment]
```js

exports.createResolvers = ({ createResolvers }) => {
  // const resolvers = {
  //   // Author: {
  //   //   fullName: {
  //   //     resolve: (source, args, context, info) => {
  //   //       return source.firstName + source.lastName
  //   //     }
  //   //   },
  //   // },
  //   Query: {
  //     allPosts: {
  //       type: ['MarkdownRemark'],
  //       resolve: (source, args, context, info) => {
  //         const posts = context.nodeModel.getAllNodes({ type: 'MarkdownRemark' })
  //         return posts.filter(post => post.fields.type = 'posts')
  //       }
  //     }
  //   }
  // }
  // createResolvers(resolvers)
}

exports.setFieldsOnGraphQLNodeType = ({ type }, options) => {
  if (!['Author', 'Category', 'Tag'].includes(type.name)) return

  const typeName = type.name.toLowerCase()
  const defaults = options.taxonomies[typeName]

  return {
    type: {
      type: 'String',
      resolve: () => typeName
    },
    template: {
      type: 'String',
      resolve: source => source.template || defaults.template
    },
    permalink: {
      type: 'String',
      resolve: source => generatePermalink(
        source.permalink || defaults.permalink,
        { slug: source.slug || kebabCase(source.name) }
      )
    },
    slug: {
      type: 'String',
      resolve: source => source.slug || kebabCase(source.name)
    }
  }
}
```

**Comment by zce** [comment]
```js
const { load } = require('js-yaml')
const { singular } = require('pluralize')
const { upperFirst, camelCase, kebabCase } = require('lodash')

exports.onCreateNode = async ({
  node,
  actions,
  loadNodeContent,
  createNodeId,
  createContentDigest
}, options) => {
  if (node.internal.mediaType !== 'text/yaml') return

  const defaults = options[node.name] || {}
  const content = await loadNodeContent(node)
  const parsedContent = load(content)

  const list = Array.isArray(parsedContent) ? parsedContent : [parsedContent]

  const type = upperFirst(camelCase(singular(node.name)))

  list.forEach((item, i) => {
    const data = { ...defaults, ...item }

    // taxonomy defaults
    if (['authors', 'categories', 'tags'].includes(node.name)) {
      data.slug = data.slug || kebabCase(data.name)
      data.type = data.type || singular(node.name)
      if (/{([a-z_]+)}/.test(data.permalink)) {
        data.permalink = data.permalink.replace(/{([a-z_]+)}/g, (_, key) => {
          if (data.hasOwnProperty(key)) return data[key]
          throw new Error(`Permalink template does not support {${key}} Tag`)
        })
      }
    }

    const yamlNode = {
      ...data,
      id: data.id || createNodeId(`${node.id} [${i}] >>> YAML`),
      parent: node.id,
      internal: {
        contentDigest: createContentDigest(data),
        type
      }
    }

    actions.createNode(yamlNode)
    // actions.createParentChildLink({ parent: node, child: yamlNode })
  })
}
```

**Comment by zce** [comment]
## site config

```yml
# https://github.com/hexojs/hexo-starter/blob/master/_config.yml

url: https://blog.zce.me # no trailing slash!

name: Lei’s
title: Lei’s Personal Website
description: Thoughts, stories and ideas. (Developing, coming)
slogan: MAKE IT BETTER!
keywords: [zce, blog, personal, homepage]

author:
  name: Lei Wang
  email: w@zce.me
  url: https://zce.me

language: en

# inline svg instead
# logo: images/logo.svg
cover: images/cover.jpg

navigation:
  - text: Home
    link: /
  - text: Blog
    link: /blog/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Discuss
    link: /discuss/

socials:
  - name: Twitter
    link: https://twitter.com/w_zce
  - name: Facebook
    link: https://www.facebook.com/zccce
  - name: LinkedIn
    link: https://www.linkedin.com/in/zceme
  - name: GitHub
    link: https://github.com/zce
  - name: YouTube
    link: https://www.youtube.com/channel/UCFUwWB0v2qYqLaB95z1nv9Q
  - name: Weibo
    link: https://weibo.com/zceme
  - name: Weixin
    link: ~
  - name: QQ
    link: ~
  - name: Youku
    link: https://i.youku.com/zcezce
  - name: Bilibili
    link: https://space.bilibili.com/210242179

links:
  - text: Story
    link: /story/
  - text: About
    link: /about/
  - text: Contact
    link: /contact/
  - text: Archive
    link: /archive/
  - text: Privacy
    link: /privacy-policy/
  - text: Terms
    link: /terms-of-service/

subscription:
  name: ITBetter
  qrcode: https://s.uieee.com/qrcode/wedn.jpg
  link: ~

card:
  image: images/unknown.jpg

disqus:
  shortname: zce-sandbox
```
